### ISSUE TITLE
Publish to Maven 

### ISSUE THREAD

**Issue by sirbris** [parttio/Animator#2]
Hi... thanks for updating the Animator to Vaadin 8! Could you please publish the current version to Maven?

**Comment by samie** [comment]
This seems to be issue in Directory Maven sync. We're investigating it.

**Comment by wbadam** [comment]
@sirbris it should be fixed now, please try to downloading again.

**Comment by samie** [comment]
Just get the pom.xml snippet from https://vaadin.com/directory/component/animator

**Comment by wbadam** [comment]
Actually, vaadin.com still says
> This component or version has not been published in Maven.

@samie does that depend on which node is serving my request?

**Comment by wbadam** [comment]
Seems like it does, since the snippet appears for a different session.

**Comment by samie** [comment]
Which is the version number here? I checked with 3.0.0, and that got redeployed. But are there several versions missing now?

**Comment by wbadam** [comment]
It's 3.0.0, and it seems to be working good now. The Directory didn't seem to pick up the changes for several hours and shown that it was not published on Maven. It may have to do with caching in the Directory or the nodes serving the site because it seemed to depend on the browser session.

**Comment by sirbris** [comment]
Thanks, working now!
