### ISSUE TITLE
Client side exception when triggering animation

### ISSUE THREAD

**Issue by mordechaim** [parttio/Animator#3]
Very new to Animator add-on and to Vaadin in general so it might be a trivial issue.

After trying the animator and seeing not working, I added `?debug` to the url, and this is the result

![capture](https://user-images.githubusercontent.com/12547785/34238967-905cb3cc-e5d2-11e7-924b-876c32a7caeb.PNG)

**Comment by wbadam** [comment]
Hi, for all add-ons, you need to have the add-on's widgetset inherited in your own widgetset. This should happen automatically in case there is no manual modification in your .gwt.xml file.

Please locate your `.gwt.xml` file and add the line `<inherits name="org.vaadin.jouni.animator.AnimatorWidgetset" />`, then recompile your widgetset with e.g. the plugin or the `mvn clean install` command.

**Comment by mordechaim** [comment]
Thanks, works.
