### ISSUE TITLE
Not working on vaadin 8.2

### ISSUE THREAD

**Issue by utrucceh** [parttio/Animator#4]
I put this double lib
'org.vaadin.addons:animator:3.0.0'
'org.vaadin.addons:dom:0.1.0'

And test via example code
But not working
[https://github.com/parttio/Animator/blob/master/demo/src/main/java/org/vaadin/jouni/animator/AnimatorTestUI.java](url)

**Comment by wbadam** [comment]
Hi,
Make sure you have the necessary widgetsets inherited. You need at least the following in your gwt.xml.
```
    <inherits name="org.vaadin.jouni.animator.AnimatorWidgetset" />
    <inherits name="com.vaadin.DefaultWidgetSet" />
    <inherits name="org.vaadin.jouni.dom.DomWidgetset" />
```
Also, please refer to #3 for details.

**Comment by utrucceh** [comment]
Thanks
